name: Atualizar Dados na Planilha

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      GOOGLE_SHEETS_SPREADSHEET_KEY: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.4  # Versão mais recente que suporta Node.js 16

      - name: Set up Python
        uses: actions/setup-python@v2.4.2  # Versão mais recente que suporta Node.js 16
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python app.py
        env:
          GOOGLE_SHEETS_JSON_KEY_PATH: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          GOOGLE_SHEETS_SPREADSHEET_KEY: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_KEY }}
