name: Atualizar Dados na Planilha

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      GOOGLE_SHEETS_SPREADSHEET_KEY: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Substitua pela versão específica do seu projeto, se necessário

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            sudo apt-get install python3-distutils  # Adicione esta linha para instalar python3-distutils
            sudo apt-get install python3-distutils  # Adicione esta linha para instalar distutils
            python -m pip install -r requirements.txt
            python -m pip install python-decouple
      
      - name: Run Python script
        run: |
          echo "Iniciando GitHub Actions Workflow"
          python app.py
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          GOOGLE_SHEETS_SPREADSHEET_KEY: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_KEY }}
